### ISSUE TITLE
No license information found and Validation for licenses of type File not yet supported

### ISSUE THREAD

**Issue by marius-muntean** [sensslen/nuget-license#109]
Hi and many thanks for this tool! I started using it after `dotnet-project-licenses` was deprecated.

In my project I'm using the following NuGets:
https://www.nuget.org/packages/RawRabbit
https://www.nuget.org/packages/RawRabbit.Extensions
https://www.nuget.org/packages/RawRabbit.Logging.Serilog

In the Error column I get `No license information found`.

For these NuGets:
https://www.nuget.org/packages/CompareNETObjects
https://www.nuget.org/packages/EFCore.BulkExtensions.PostgreSql
https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client
https://www.nuget.org/packages/MockQueryable.Moq
https://www.nuget.org/packages/PdfSharpCore

I get `Validation for licenses of type File not yet supported`.

Is there a setting I can change to support them as well or is it something more complex?

**Comment by sensslen** [comment]
Supporting file type licenses is a complex task, as it requires matching the license text to a license type. The license text may or may not contain modifications to the license template (e.g. adding names). See https://github.com/sensslen/nuget-license/issues/56 for further explanation. You can use `-override|--override-package-information <OVERRIDE_PACKAGE_INFORMATION>` to override license information which will allow you to specify the license manually. See https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/overwritePackageInformation.json for an example file to pass in.

**Comment by sensslen** [comment]
Closing this issue, as there are currently no plans in supporting file type licenses and also this was requested with #56 already and therefore is a dupe
