### ISSUE TITLE
Overwritten License download fails with 404, but URL exists

### ISSUE THREAD

**Issue by janpahnen** [sensslen/nuget-license#119]
Hi,

I'm overwriting package URLs for some proprietary licenses, and their download fails with a 404. But if I open the URL in the browser the site is found. For example this:
```
{
        "Id": "Microsoft.Web.WebView2",
        "Version": "1.0.2903.40",
        "ProjectUrl": "https://aka.ms/webview",
        "Copyright": "\u00A9 Microsoft Corporation. All rights reserved.",
        "Authors": "Microsoft",
        "License": "Proprietary",
        "LicenseUrl": "https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2903.40/License"
}
```

this is the license url provided by the NuGet page, and I just want this site to be downloaded. Is there anything I'm doing wrong in the overwrite?

**Comment by janpahnen** [comment]
I've just realized that it uses the information from the "License" field to download the license, and not from the url. Since there is no license on nuget.org with the name "Proprietary", it fails.
But how can I make the tool to use the LicenseUrl for downloading?

**Comment by sensslen** [comment]
What you're trying to do is something that is not currently supported by nuget-license. The expectation is that License would almost always be a [SPDX](https://spdx.org/licenses/) license expression and thus nuget.org would provide the necessary means to download it. For your case: You're looking at a MIT license. So to resolve your immediate issue, instead of putting `"Proprietary"` as license, you can use `"MIT"` and your problem goes away.

**Comment by janpahnen** [comment]
Thanks for your quick response! Unfortunately this is not the only NuGet package with this problem, and the others aren't MIT but custom Microsoft types. But since I do all the license processing in Powershell, I set it to MIT so it works, and set it afterwards with the correct information and download these few licenses in Powershell myself.

**Comment by sensslen** [comment]
If you do the download in powershell anyways, there's no need to specify a specific license. you can just disable the download and nuget-license will take any license

**Comment by janpahnen** [comment]
It's only 4 licenses with this problem, all other NuGet packages (and there are many across all projects) should still be downloaded by your tool. Hopefully Microsoft migrates these 4 projects to "MIT" sometime, so I don't need this special handling.
