### ISSUE TITLE
Program produces exit code > 0 even on successful license downloads

### ISSUE THREAD

**Issue by Bomret** [sensslen/nuget-license#120]
I want to run this tool as part of our publish workflow so it automatically downloads all licenses into a local folder. The workflow is run via shell commands. The command I currently use is `dotnet tool run nuget-license -i '*.csproj' -d 'licenses'`. It downloads all the licenses in HTML format but produces the exit code `2` which breaks as a non-0 exit code is considered a failure.
Apparently the tool runs a validator on the licences and prints out the count of licenses that fail to validate. I think this should be changed. If there are validation errors, these should rather be printed to the StdErr stream. The tool should IMHO only produce a non-0 exit code when the tool runs into a real error. Or am I missing a command line switch somewhere that would prevent this behaviour?

**Comment by sensslen** [comment]
Well the tool was written to **validate** licenses which is why validation failures are considered real errors. You should rather make sure there are no validation errors.

**Comment by sensslen** [comment]
You can still use the tool by providing an arbitrary url to license map...
