### ISSUE TITLE
Documented short flag -fo (short for --file-output) doesn't work 

### ISSUE THREAD

**Issue by princefishthrower** [sensslen/nuget-license#122]
As the title states, the short version of the `--file-output` flag `-fo` doesn't work. Output from my CI / CD workflow:

```
nuget-license -i MySolution.sln -o json -fo "${CI_PROJECT_DIR}/doc/licenselist/license.json"
Unrecognized option '-fo'
Did you mean this?
    o
```

I'm using the latest version, 3.0.13

Any ideas what could be wrong here? Do I need to capitalize `json` to `Json`? I can't imagine that affects the `-fo` flag though...

**Comment by sensslen** [comment]
That's an easy one. The file output addition has not yet made it's way into a release. I can kick off a release in a minute for you.... That would then be 3.0.14.....

**Comment by sensslen** [comment]
You can follow the build here: https://github.com/sensslen/nuget-license/actions/runs/12282433750/job/34273635059

**Comment by princefishthrower** [comment]
Perfect, thank you!
