### ISSUE TITLE
export-licenses-texts option is missing

### ISSUE THREAD

**Issue by trampster** [sensslen/nuget-license#14]
Are there any plans to reintroduce the --export-licenses-texts option, as we need this to comply with many open source licenses which explicitly require you include the actual license text

For example BSD says:

> * Redistributions in binary form must reproduce the above copyright
>     notice, this list of conditions and the following disclaimer in the
>     documentation and/or other materials provided with the distribution.

**Comment by sensslen** [comment]
There is the option to export the licenses in HTML form. This option downloads all licenses in HTML form from the provided license url. Licenses that specify a SPDX identifier are not downloaded, as these usually don't provide a license to download. I guess to do what you want you would need to do 2 things:
- Convert the license html's downloaded to a text file (not a trivial task - and I think this is better suited for a post processing step with a dedicated application)
- Download or find a different way of providing the licenses specified using a SPDX identifier.

I don't currently plan to include any of this into the application as it is. The main reason being that I consider the tasks at hand not core responsibility of an application that extracts and validates licenses. I would argue that this is post processing that can happen in a follow up step.
