### ISSUE TITLE
Is the plan to add support for projects using packages.config?

### ISSUE THREAD

**Issue by notofug** [sensslen/nuget-license#15]
Asking in an issue since no discussion activated here :-)

I see ref to packages.config-based projects and would love support for that. 

I have mixed environment setup with C# (reference-style) and C++ projects that must use packages.config-style. (e.g : https://github.com/nlohmann/json/issues/1132#issuecomment-452250255)

![image](https://github.com/sensslen/nuget-license/assets/40484721/e4df0e69-7508-4739-a8f5-d01ede8591e7)

Beeing able to handle 'everything' would be great 👍

**Comment by sensslen** [comment]
Projects using packages.config should be supported - that said: I have not done a lot of testing around that. There is a test that runs on CI testing the ability to handle packages.config projects.... See https://github.com/sensslen/nuget-license/tree/main/tests/targets/PackagesConfigProject

**Comment by notofug** [comment]
I saw that test-project and that made me optimistic, but then I saw this among the testcases :
https://github.com/sensslen/nuget-license/blob/beae98cc44e6d3257a34fa54724a34b0c3f24f1f/tests/NuGetUtility.Test/ReferencedPackagesReader/ReferencedPackagesReaderIntegrationTest.cs#L74

Anyway , great that it is on the table, I may have a go at something!

**Comment by sensslen** [comment]
Oh, right - there was something. If you find a way to actually support legacy projects, I'll happily accept. However I seem to recall that packagesconfig projects are not supported by the nuget library provided by microsoft.

**Comment by sensslen** [comment]
This has been resolved with #17. Thank you very much for your contribution!
