### ISSUE TITLE
[Question] Print the projects of specific nuget?

### ISSUE THREAD

**Issue by LiorBanai** [sensslen/nuget-license#18]
Hi 
in https://github.com/tomchavakis/nuget-license/issues/192 I asked about included the nuget in each project.
it was added in MR https://github.com/tomchavakis/nuget-license/pull/199

Any plan to add this (if not yet added)?

**Comment by sensslen** [comment]
Can you please add more context to this request? Why would you want this information? How does this option play with the `-t` option?

**Comment by LiorBanai** [comment]
basically I run the tool on solution (not project) so it will be good to see dependency per prjoct in solution. If I have other project in solution that are not for prodcution it will be good to know if those have non free licenses. right now there is just a list and you don't know which licene came from which project.

**Comment by LiorBanai** [comment]
there is already open pr on the upstream repository. It jsut a matter of adding it here no?

**Comment by sensslen** [comment]
@LiorBanai can you please check whether #23 resolves your issue?

**Comment by LiorBanai** [comment]
I'll check and update. Thanks!

**Comment by LiorBanai** [comment]
Hi @sensslen 
it is not clear to me if this is merged or not? Should I test it from dev branch?

**Comment by sensslen** [comment]
@LiorBanai Yes, I'm not going to merge until I get your review - There's no use adding more code if it's of no use. Please check out the branch, build and test and check whether the implementation fits at least your needs....

**Comment by sensslen** [comment]
@LiorBanai were you able to test?

**Comment by sensslen** [comment]
You can run the executable produced by your build just like the one installed via nuget. The only difference will be that you have to call the executable (NugetUtility.dll I think) directly…Von meinem iPhone gesendetAm 26.01.2024 um 10:24 schrieb Lior Banai ***@***.***>:﻿
tried it now but not sure how to check to honest.
Is there a unit test tha tI can just run on specific solution project and see the output?

**Comment by LiorBanai** [comment]
@sensslen great. I'lll check and update you. Thanks for all the efforts

**Comment by sensslen** [comment]
@LiorBanai please let me know whether you're ok with the changes. Otherwies I'll have to close the PR, as it gets difficult to maintain with all the other changes that go in....

**Comment by LiorBanai** [comment]
@sensslen I was not able to teset it, too many issues and error running for mthe dev branch.
you cna close it as this is not very important to my use case..

thanks for your efforts

**Comment by sensslen** [comment]
Closing the issue as of above conversation
