### ISSUE TITLE
Support for multiple licenses

### ISSUE THREAD

**Issue by jonaswirth** [sensslen/nuget-license#44]
The package CsvHelper (https://joshclose.github.io/CsvHelper/) provides "MS-PL OR Apache-2.0" as license information. The check fails since the value is not present in our allow list. In the previous version we didn't have this issue.

As a workaround I solved it by setting the license manually with the "--override-package-information" option to "Apache-2.0". But it would be great if the tool could handle multiple licenses out of the box.

**Comment by sensslen** [comment]
@jonaswirth can you please check if #45 resolves this issue?

**Comment by sensslen** [comment]
@jonaswirth I'd really appreciate if I could get feedback on whether #45 will resolve your issue. Please go ahead and check out the source code, build the project and run it against your application.
