### ISSUE TITLE
no overwrite of properties possible

### ISSUE THREAD

**Issue by cyclingJW** [sensslen/nuget-license#53]
Is this intended behaviour that it's not possible to overwrite properties like Authors?
 {
"PackageId": "Microsoft.VisualStudio.Azure.Containers.Tools.Targets",
"PackageVersion": "1.20.1",
"PackageProjectUrl": "",
"Copyright": "",
"Authors": "",
"License": "MIT",
"LicenseInformationOrigin": 4
 },

**Comment by sensslen** [comment]
Hi @cyclingJW this is not intentional but has not yet been implemented. Implementing those fields should be fairly straight forward. Feel free to submit a PullRequest.

**Comment by sensslen** [comment]
@cyclingJW would you mind checking if #68 resolves the issue for you?
