### ISSUE TITLE
Ignore not working?

### ISSUE THREAD

**Issue by svelue** [sensslen/nuget-license#60]
Hi,

maybe I don't understand the usage, but for me it seems like the ignore functionality is not working correctly.

I'm calling `nuget-license -i xxx.sln -ignore ./exclude.json -o jsonPretty` in the solution folder. The exclude.json file contains `["*.*"]` but i still get several licenses printed. Shouldn't the response be empty? On the other hand, without the file there are more licenses in the response - the remaining ones are not part on a single csproj file but parts of several ones.

Initially I tried to exclude all tests projects via `["*Tests.csproj", "*Test.csproj"]` but that was not working at all.

Am I doing it wrong? Or is there a bug??

**Comment by sensslen** [comment]
The ignore option is not there to exclude projects. It's there to ignore packages by name. This isuseful for packages that don't specify a license (e.g. in house packages).

It is expected that the -i option specifies a list of projects to analyze...

**Comment by svelue** [comment]
Ahh, that makes sense, thx.
I guess instead of the solution file I'll go with the list of all projects excluding the testprojects then.
