### ISSUE TITLE
Fix ambiguity with --error-only flag

### ISSUE THREAD

**Issue by Fedoop1** [sensslen/nuget-license#63]
Good time of day,

I'm willing to submit a request to remove ambiguity with the `--error-only` flag. 
From my understanding, it should print output only when there are any validation errors, but at the moment of writing it prints whole output when there are no validation errors. 
>This flag allows to print only packages containing validation errors (if any). This allows the user to focus on errors instead of having to deal with many properly validated

I briefly looked into the code and found that `errorColumnDefinition` is always disabled in `TableOutputFormatter.cs` and `JsonOutputFormatter.cs` probably should return on line 36 when there are no results with validation errors.
Could you please confirm or deny my assumption? If it's so, I can submit a PR addressing this issue.

Best regards,
Nikita

**Comment by sensslen** [comment]
Hi @Fedoop1 you are right. This is ambiguous. Looking at this now, the output should probably print an empty array if there are no errors... For the json output I would also still print an empty array...

That said, this should happen if you simply remove the check on whether the error list is empty...

Regards, Simon

**Comment by Fedoop1** [comment]
Thanks for the quick reply. Glad we're on the same page. Should I send a PR with the fix or will you handle it yourself?

**Comment by sensslen** [comment]
Please do submit a PR if you got time to work on it....
