### ISSUE TITLE
Command line option to specify output line endings?

### ISSUE THREAD

**Issue by patheikkinen** [sensslen/nuget-license#65]
I'm working on a project which generates a LICENSES.md file in a PowerShell script like this:

`dotnet nuget-license -i $solution > ./licenses/LICENSES.md`

The rest of the project uses unix-style LF line endings but this produces CRLF, which causes some annoyance.

Would it be possible to add a command line option to optionally specify unix-style line endings instead of environment default?

I understand this might look funny if the output is printed on screen, but it would be for redirecting to file. I believe current PowerShell version treats pipes as raw byte for byte and doesn't touch the line endings, so I imagine this should suffice to get the pipeline working perfectly.

**Comment by sensslen** [comment]
Hi @patheikkinen I don't feel like adding command line options like this. This would clutter the command line interface enormously and add testing burden. Why don't you use something similar to https://stackoverflow.com/questions/19127741/replace-crlf-using-powershell to modify the line endings in the pipe?

**Comment by sensslen** [comment]
Closing as this is a niche scenario and would clutter the command line interface
