### ISSUE TITLE
Supplement or replace the information in the package

### ISSUE THREAD

**Issue by Diddlik** [sensslen/nuget-license#74]
I have a package ‘Standard.Licensing’
with ‘dotnet-project-licenses’ I get the following output:
```
 {
    ‘PackageName": “Standard.Licensing”,
    ‘PackageVersion": “1.2.0”,
    ‘PackageUrl": “https://www.junian.dev/Standard.Licensing/”,
    ‘Copyright": “Copyright (c) 2018 - 2024”,
    ‘Authors": [
      ‘Junian Triajianto’
    ],
    ‘Description": “Easy-to-use licensing library for .NET and .NET Framework products.”,
    ‘LicenceUrl": “https://www.nuget.org/packages/Standard.Licensing/1.2.0/License”,
    ‘LicenceType": ’LICENSE’
  },

```
with nuget-license this:

```
{
    ‘PackageId": “Standard.Licensing”,
    ‘PackageVersion": “1.2.0”,
    ‘PackageProjectUrl": “https://www.junian.dev/Standard.Licensing/”,
    ‘Copyright": “Copyright (c) 2018 - 2024”,
    ‘Authors": “Junian Triajianto”,
    ‘ValidationErrors": [
      {
        ‘Error": “Validation for licences of type File not yet supported”,
        ‘Context": ’I:\\Coding\\DGO_NG\\DGO.License\\DGO.DGOLicense.csproj’
      },
      {
        ‘Error": “Validation for licences of type File not yet supported”,
        ‘Context": ’I:\\Coding\\DGO_NG\\LicenseManager.Core\\LicenseManager.Core.csproj’
      }
    ],
    ‘LicenceUrl": “https://aka.ms/deprecateLicenseUrl”,
    ‘LicenseInformationOrigin": 2
  },
```

How can I work around this, or can I somehow adjust the licence URL and type myself so that no error message appears?

**Comment by sensslen** [comment]
You should be using the override option. See https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/overwritePackageInformation.json for examples.

**Comment by sensslen** [comment]
The reaseon for this difference is because nuget-license actually uses the license expression whenever possible and only uses license url as a last resort....

**Comment by Diddlik** [comment]
would it be enough to put this into override json or I need to put all information from package?:
 [
    {
        "Id": "Standard.Licensing",
        "License": "MIT"
    }
]

**Comment by sensslen** [comment]
> would it be enough to put this into override json or I need to put all information from package?:
> 
>  [
> 
>     {
> 
>         "Id": "Standard.Licensing",
> 
>         "License": "MIT"
> 
>     }
> 
> ]

You will also need to specify the version - that's it...

**Comment by Diddlik** [comment]
Ok, it seems to work! Thank you!
