### ISSUE TITLE
Can not figure out the structure required for --override-package-information | missing documentation

### ISSUE THREAD

**Issue by hbertsch** [sensslen/nuget-license#80]
I'm having trouble figuring out the correct JSON structure required for the `--override-package-information` option in the `nuget-license` tool. The available documentation does not provide clear guidance on how to format the override JSON file. I tried various approaches and also had a look into the source but no success so far. Can you please provide me with a sample. It would be greatly appreciated!

**Comment by sensslen** [comment]
Please find an example here: https://github.com/sensslen/nuget-license/blob/main/.github/workflows/assets/Tests/overwritePackageInformation.json. I'd be very happy if you could help improve the documentation. I know it's lacking but I currently do not have the time to really work on that. Feel free to file Pull Requests for that.

**Comment by hbertsch** [comment]
Worked perfectly. I was not looking into the .github section of the project. Maybe it would be good to somehow set a link or such to the examples :) 
Appreciate your swift response and the project!
